### ISSUE TITLE
Suggestion: Quick generation of a new wallet

### ISSUE THREAD

**Issue by Joohansson** [linuxserver/nano-wallet#4] opened 2020-06-03 17:29 UTC
I find it a bit complicated to click the link at the bottom, generate a wallet and then copy the right field over to the first page (at the same time save the seed in a secure location). It's multiple copy/paste. I think it would be better to have a button for "New Wallet" on the front page that would generate the seed (and private key with account index 0). And suggest that the user save the seed before they can log in! Optionally also allow the user to export the seed from the settings page once they are logged in.

**Comment by thelamer** [comment] 2020-06-03 20:22
I think you might be thinking of this from the angle of using other Nano wallets. 
I agree all of these features would make the experience easier there is no doubt about that. 
The issue is that some of the functionality of the wallet should be self documenting through user experience. 
While tedious to not only set your seed manually using the form and not being able to display it from the wallet view , that experience in itself absolves us of the responsibility of people asking about lost wallet seed/key and informs the user through manual work that this wallet does not store their info ever. 
We know with 100% certainty that the user has that seed outside of the browser and when and if they are asked where they put it the answer will always be "in a text file" or "password manager" etc etc. At that moment it will be self evident to the user that they messed up not us.

**Comment by Joohansson** [comment] 2020-06-04 12:42
Thats a good point

**Comment by thelamer** [comment] 2020-06-06 17:51
With the continued optimizations to the generate page and the paper wallet addition I am gonna close this out. 
In the future we might want to re-visit the possibility of a quick login concept if the project ever gets to a point where it is leveraging storage or external crypto devices, but I do not see that happening medium/short term.

**Closed by thelamer** 2020-06-06 17:51 UTC
